In [1]:
import numpy as np

In [18]:
import numpy as np

# Confusion Matrix

confusion_matrix = np.zeros([2,2])
# print(confusion_matrix)
# print(confusion_matrix[0][0])

# input:  2 liste 

y_real = [1, 0, 1, 1]
y_pred = [1, 0, 0, 1]

for i in range(len(y_real)): # ciclo su tutti gli indici del campione 
    real = y_real[i] # etichetta real del i-esimo campione
    predittivo = y_pred[i] # etichetta predetta per lo stesso campione 
    confusion_matrix[predittivo][real] += 1 # aggiorno la confusion matrix, aggiungendo 1 alla cella corrispondente alla coppia (predittivo, real)

print(confusion_matrix)

[[1. 1.]
 [0. 2.]]


In [19]:
# Esempio studente 2: Nicolàs
import numpy as np

# Confusion Matrix


# print(confusion_matrix)
# print(confusion_matrix[0][0])
# input:  2 liste 

y_real = [1, 0, 1, 1,2,2]
y_pred = [1, 0, 0, 1,2,0]

valori_unici = list(set(y_real))
n_classi= len(valori_unici)

confusion_matrix = np.zeros([n_classi,n_classi])
for i in range(len(y_real)): # ciclo su tutti gli indici del campione 
    print("i= ",i)
    real = y_real[i] # etichetta real del i-esimo campione
    predittivo = y_pred[i] # etichetta predetta per lo stesso campione 
    print("real= ",real)
    print("predittivo= ",predittivo)
    confusion_matrix[real][predittivo] += 1 # aggiorno la confusion matrix, aggiungendo 1 alla cella corrispondente alla coppia (predittivo, real)
    print(confusion_matrix)
    print(confusion_matrix) 

i=  0
real=  1
predittivo=  1
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
i=  1
real=  0
predittivo=  0
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
i=  2
real=  1
predittivo=  0
[[1. 0. 0.]
 [1. 1. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [1. 1. 0.]
 [0. 0. 0.]]
i=  3
real=  1
predittivo=  1
[[1. 0. 0.]
 [1. 2. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [1. 2. 0.]
 [0. 0. 0.]]
i=  4
real=  2
predittivo=  2
[[1. 0. 0.]
 [1. 2. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [1. 2. 0.]
 [0. 0. 1.]]
i=  5
real=  2
predittivo=  0
[[1. 0. 0.]
 [1. 2. 0.]
 [1. 0. 1.]]
[[1. 0. 0.]
 [1. 2. 0.]
 [1. 0. 1.]]


In [ ]:
a.np.zeros([2,2])

In [ ]:
accuracy = (a[0,0] + a[1,1]) / a.sum()
print(accuracy)


In [24]:
#il mio metodo
a = [[0, 0],
     [13, 0]]


totale = 0
corretti = 0

#Sommo il totale degli esempi
for i in range(2):
    for j in range(2):
        totale += a[i][j]

print("Totale:", totale) 


#sommo solo le predizioni corrette
for i in range(2):
    corretti += a[i][i]

print("solo quelli corretti:" ,corretti)  


#calcolo l'accuracyy

accuracy = corretti / totale
print("accuracy:" ,accuracy)  # 0.0







SyntaxError: invalid syntax. Perhaps you forgot a comma? (4188554033.py, line 14)